name: Format

on:
  pull_request:
    branches: [main]

jobs:

  audit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Run fmt test script
      run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
